[2024-03-21T21:24:00.487+0000] {processor.py:161} INFO - Started process (PID=1912) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:00.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:24:00.492+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:24:00.491+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:00.495+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:24:00.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:24:00.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:00.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.081 seconds
[2024-03-21T21:24:30.723+0000] {processor.py:161} INFO - Started process (PID=1928) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:30.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:24:30.726+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:24:30.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:30.731+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:24:30.729+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:24:30.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:24:30.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.039 seconds
[2024-03-21T21:25:00.945+0000] {processor.py:161} INFO - Started process (PID=1944) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:00.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:25:00.948+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:25:00.947+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:00.952+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:25:00.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:25:00.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:00.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.038 seconds
[2024-03-21T21:25:31.199+0000] {processor.py:161} INFO - Started process (PID=1960) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:31.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:25:31.201+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:25:31.201+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:31.204+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:25:31.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:25:31.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:25:31.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.034 seconds
[2024-03-21T21:26:01.384+0000] {processor.py:161} INFO - Started process (PID=1977) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:01.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:26:01.387+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:26:01.387+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:01.391+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:26:01.390+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:26:01.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:01.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.057 seconds
[2024-03-21T21:26:32.029+0000] {processor.py:161} INFO - Started process (PID=1994) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:32.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:26:32.032+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:26:32.032+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:32.049+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:26:32.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:26:32.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:26:32.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.062 seconds
[2024-03-21T21:27:02.260+0000] {processor.py:161} INFO - Started process (PID=2010) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:02.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:27:02.262+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:27:02.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:02.265+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:27:02.265+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:27:02.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:02.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.035 seconds
[2024-03-21T21:27:32.459+0000] {processor.py:161} INFO - Started process (PID=2027) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:32.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:27:32.462+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:27:32.462+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:32.466+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:27:32.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:27:32.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:27:32.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.039 seconds
[2024-03-21T21:28:02.679+0000] {processor.py:161} INFO - Started process (PID=2044) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:02.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:28:02.682+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:28:02.681+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:02.686+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:28:02.685+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:28:02.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:02.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.036 seconds
[2024-03-21T21:28:32.881+0000] {processor.py:161} INFO - Started process (PID=2060) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:32.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:28:32.884+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:28:32.883+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:32.887+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:28:32.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:28:32.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:28:32.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.041 seconds
[2024-03-21T21:29:03.347+0000] {processor.py:161} INFO - Started process (PID=2076) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:03.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:29:03.351+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:29:03.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:03.357+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:29:03.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:29:03.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:03.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.072 seconds
[2024-03-21T21:29:33.900+0000] {processor.py:161} INFO - Started process (PID=2092) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:33.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:29:33.929+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:29:33.919+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:34.017+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:29:34.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:29:34.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:29:34.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.539 seconds
[2024-03-21T21:30:05.218+0000] {processor.py:161} INFO - Started process (PID=2108) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:05.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:30:05.230+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:30:05.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:05.289+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:30:05.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:30:05.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:05.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.547 seconds
[2024-03-21T21:30:35.937+0000] {processor.py:161} INFO - Started process (PID=2124) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:36.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:30:36.032+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:30:36.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:36.089+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:30:36.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:30:36.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:30:36.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.368 seconds
[2024-03-21T21:31:06.549+0000] {processor.py:161} INFO - Started process (PID=2140) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:06.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:31:06.563+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:31:06.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:06.603+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:31:06.602+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:31:06.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:06.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.090 seconds
[2024-03-21T21:31:36.859+0000] {processor.py:161} INFO - Started process (PID=2156) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:36.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:31:36.863+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:31:36.862+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:36.867+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:31:36.866+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:31:36.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:31:36.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.045 seconds
[2024-03-21T21:32:07.118+0000] {processor.py:161} INFO - Started process (PID=2172) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:07.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:32:07.123+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:32:07.123+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:07.129+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:32:07.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:32:07.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:07.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.060 seconds
[2024-03-21T21:32:37.438+0000] {processor.py:161} INFO - Started process (PID=2189) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:37.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:32:37.449+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:32:37.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:37.496+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:32:37.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:32:37.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:32:37.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_to_mysql.py took 0.101 seconds
[2024-03-21T21:33:08.079+0000] {processor.py:161} INFO - Started process (PID=2209) to work on /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:33:08.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_to_mysql.py for tasks to queue
[2024-03-21T21:33:08.170+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:33:08.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/load_to_mysql.py
[2024-03-21T21:33:08.220+0000] {logging_mixin.py:188} INFO - [2024-03-21T21:33:08.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_to_mysql.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_to_mysql.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-03-21T21:33:08.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_to_mysql.py
